# Generated by Django 2.2.6 on 2020-02-15 16:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import unrest.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0002_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('google_id', models.CharField(max_length=32)),
                ('attachment_number', models.IntegerField()),
                ('source_email', models.CharField(max_length=256)),
                ('from_email', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('new', 'new'), ('rejected', 'rejected'), ('completed', 'completed')], default='new', max_length=16)),
                ('status_note', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_hash', models.BigIntegerField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, unrest.models.JsonMixin),
        ),
    ]
